force-app/main/default/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/Log__e/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/Log__e/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Log_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/packaged/objects/LogSetting__mdt/LogSetting__mdt.object-meta.xml
<CustomObject>
    <label>LogSetting</label>
    <pluralLabel>LogSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogSetting__mdt/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>LogLevel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>NONE</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogSetting__mdt/fields/LogViaEvents__c.field-meta.xml
<CustomField>
    <fullName>LogViaEvents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Via Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogSetting__mdt/fields/LogViaObject__c.field-meta.xml
<CustomField>
    <fullName>LogViaObject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Via Object</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogSetting__mdt/fields/LogViaSystemDebug__c.field-meta.xml
<CustomField>
    <fullName>LogViaSystemDebug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Via System Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogSetting__mdt/fields/Mute__c.field-meta.xml
<CustomField>
    <fullName>Mute__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Mute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Log.cls
public without sharing class Log {
    private static Log instance = null;

	private static Log__e currentEvent = null;

    private static LogEntry__c currentRecord = null;

    private static final Pattern STACK_LINE = Pattern.compile('^(?:Class\\.)?([^.]+)\\.?([^\\.\\:]+)?[\\.\\:]?([^\\.\\:]*): line (\\d+), column (\\d+)$');

    //Logger Dynamic Controls
    private Boolean mute {get; set;}
    private Boolean logViaEvents {get; set;}
    private Boolean logViaObject {get; set;}
    private Boolean logViaSystemDebug {get; set;}
    private LoggingLevel currentLogLevel {get; set;}
    /**
     * Constructor reads the MDT settings for current user if found and sets the log levels. If not found
     * System setings are read from "Org" developer name. If not found then only System debug behaviour is
     * emulated.
     */
    public Log() {
        loadLogSettings();
    }

	// Public logging methods
    public void error(Object message) {
        emit(LoggingLevel.ERROR, message, null);
	}
    public void warn(Object message) {
        emit(LoggingLevel.WARN, message, null);
	}
    public void info(Object message) {
        emit(LoggingLevel.INFO, message, null);
	}
	public void debug(Object message) {
        emit(LoggingLevel.DEBUG, message, null);
	}
    public void fine(Object message) {
        emit(LoggingLevel.FINE, message, null);
	}
    public void finer(Object message) {
        emit(LoggingLevel.FINER, message, null);
	}
    public void finest(Object message) {
        emit(LoggingLevel.FINEST, message, null);
	}
    public void put(LoggingLevel level, Object message, String source) {
        emit(level, message, 'Flow - ' + source);
	}

    //Control Methods
    public void pause() {
        mute = true;
    }
    public void resume() {
        mute = false;
    }
	
    public LoggingLevel getCurrentLogLevel() {
        return currentLogLevel;
    }

	/**
     * Actual log entry is made by this method depending on settings.  
     */ 
	private void emit(LoggingLevel level, Object message, String source) {
        //Return, if muted. 
        if(mute) {
            return;
        }
        // Don't log if current log level is set to lower than requested log level.
        if(currentLogLevel.ordinal() > level.ordinal()) {
            return;
        }
        // Resolve Apex Source code details where log is invoked from. 
        String sourcePointer =  source == null? getSourcePointer() : source;

        //Log to platform event, when enabled.
		if(logViaEvents) {
			currentEvent = new Log__e();
			currentEvent.User__c = UserInfo.getUserId();
            currentEvent.Level__c = level.name() ;
            currentEvent.Quiddity__c = Request.getCurrent().getQuiddity().name();
            currentEvent.RequestId__c = Request.getCurrent().getRequestId();
			currentEvent.Message__c = String.valueOf(message);
            currentEvent.Source__c = sourcePointer;

            System.debug(LoggingLevel.DEBUG, 'publishing message ' + currentEvent);
            Database.SaveResult result = EventBus.publish(currentEvent);
            if (!result.isSuccess()) {
                System.debug(LoggingLevel.ERROR, 'Error returned: ' + result.getErrors());
            }
		}

        //Log to custom object, when enabled.
        if(logViaObject) {
            currentRecord = new LogEntry__c();
            currentRecord.User__c = UserInfo.getUserId();
            currentRecord.Level__c = level.name();
            currentRecord.Quiddity__c = Request.getCurrent().getQuiddity().name();
            currentRecord.RequestId__c = Request.getCurrent().getRequestId();
			currentRecord.Message__c = String.valueOf(message);
            currentRecord.Source__c = sourcePointer;

            insert currentRecord;
        }

        //Log to System Debug, when enabled.
        if (logViaSystemDebug) {
			System.debug(level, message);
		}
	}

    @TestVisible
    private void loadLogSettings() {
        LogSetting__mdt logSettings = LogSetting__mdt.getInstance('UserId_' + UserInfo.getUserId());
        if(logSettings == null) {
            logSettings = LogSetting__mdt.getInstance('ProfileId_' + UserInfo.getProfileId());
        }
        if(logSettings == null) {
            logSettings = LogSetting__mdt.getInstance('System');
        }
        mute = logSettings != null ? logSettings.Mute__c : false;
        logViaEvents = logSettings != null ? logSettings.LogViaEvents__c : false;
        logViaObject = logSettings != null ? logSettings.LogViaObject__c : false;
        logViaSystemDebug = logSettings != null ? logSettings.LogViaSystemDebug__c : true;
        //Note - Finest log level enables it to reach system debug.
        currentLogLevel = logSettings != null ? LoggingLevel.valueOf(logSettings.LogLevel__c) : LoggingLevel.FINEST; 
    }
    /** 
     * This extracts code information to populate in the log object.
     */ 
	private String getSourcePointer() {
		// Note: Idea taken from https://salesforce.stackexchange.com/questions/153835
        String sourcePointer = 'UNKNOWN';
        Map<String, Object> codeDetails =  new Map<String, Object>();
		List<String> stacktrace = new DmlException().getStackTraceString().split('\n');
		for(String line : stacktrace) {
			Matcher matcher = STACK_LINE.matcher(line);
			if(matcher.find() && !line.startsWith('Class.Log.')) {
				Boolean hasNamespace = String.isNotBlank(matcher.group(3));
				if(hasNamespace) {
                    //namespace.className.methodName
                    sourcePointer = 'Apex - ' + matcher.group(1) + '.' + matcher.group(2) + '.' + prettyMethod(matcher.group(3));
				}
				else {
                    //className.methodName
                    sourcePointer = 'Apex - ' + matcher.group(1) + '.' + prettyMethod(matcher.group(2));
				}
				//Line Number
                sourcePointer += '#' + String.valueOf(matcher.group(4));
				return sourcePointer;
			}
		}
        return sourcePointer;
	}

    /**
     * Enhances method names to be more readable format. 
     */
	private String prettyMethod(String method) {
		String result = (method == null) ? 'anonymous' : method;
		return (result.contains('init')) ? 'constructor' : result;
	}

    /**
     * Static method returns the singlton instance if found or instantiates one.
     */
    public static Log me() {
        if(instance == null) {
            instance = new Log();
        }
        return instance;
    }
}