src/packaged/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/Log__e/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/Log__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/Log__e/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Log_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/packaged/classes/LogTriggerHandler.cls
/**
 * Created by jaapbranderhorst on 16/10/2024.
 */

public with sharing class LogTriggerHandler {

    private List<Log__e> events;

    public LogTriggerHandler(List<Log__e> events) {
        this.events = events;
    }

    public void handleTrigger() {
        List<LogEntry__c> logEntries = new List<LogEntry__c>();
        for (Log__e event : events) {
            logEntries.add(new LogEntry__c(
                    User__c = event.User__c,
                    Level__c = event.Level__c,
                    Quiddity__c = event.Quiddity__c,
                    RequestId__c = event.RequestId__c,
                    Message__c = event.Message__c,
                    Source__c = event.Source__c,
                    StackTrace__c = event.StackTrace__c,
                    Method__c = event.Method__c,
                    Line__c = event.Line__c
            ));
        }
        insert as system logEntries; // events must always be logged, but the automated process user runs this which has all rights.
    }

}