src/packaged/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/packaged/objects/LogEntry__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Log_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/packaged/classes/LogInvocableAction_Test.cls
/**
 * Test class for Log invocable action
 */
@IsTest
public class LogInvocableAction_Test {
    @IsTest
	private static void testMakeLogEntry() {
        List<LogInvocableAction.Request> listOfRequests = new List<LogInvocableAction.Request>();
        LogInvocableAction.Request req = new LogInvocableAction.Request();
        req.level = 'ERROR';
        req.source = 'Test_Flow_Name';
        req.message='Test Message';
        listOfRequests.add(req);
        Test.startTest();
        LogInvocableAction.makeLogEntry(listOfRequests);
        Test.stopTest();
        List<LogEntry__c> logEntries = [
                SELECT
                        Class__c,
                        CreatedById,
                        CreatedDate,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Level__c,
                        Line__c,
                        Message__c,
                        Method__c,
                        Name,
                        OwnerId,
                        Quiddity__c,
                        RequestId__c,
                        Source__c,
                        StackTrace__c,
                        SystemModstamp,
                        User__c,
                        Id
                FROM LogEntry__c];
        Assert.areEqual(1, logEntries.size());
        Assert.areEqual(req.level, logEntries[0].Level__c);
        Assert.areEqual(req.source, logEntries[0].Source__c);
        Assert.areEqual(req.message, logEntries[0].Message__c);
    } 
}